-- 001
DROP TABLE IF EXISTS Actor CASCADE;
DROP TABLE IF EXISTS CrewMember CASCADE;
DROP TABLE IF EXISTS Director CASCADE;
DROP TABLE IF EXISTS Producer CASCADE;
DROP TABLE IF EXISTS Movie CASCADE;

-- 002
DROP TABLE IF EXISTS Movie_Actor CASCADE;
DROP TABLE IF EXISTS Movie_CrewMember CASCADE;
DROP TABLE IF EXISTS Movie_Director CASCADE;
DROP TABLE IF EXISTS Movie_Producer CASCADE;

-- 003
DROP TYPE IF EXISTS commission_type CASCADE;
DROP TYPE IF EXISTS contract_type CASCADE;

DROP TABLE IF EXISTS DirectorFinance CASCADE;
DROP TABLE IF EXISTS ProducerFinance CASCADE;
DROP TABLE IF EXISTS MovieFinance CASCADE;







